//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_React.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_React.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul nu poate fi nul..
        /// </summary>
        internal static string NullRole {
            get {
                return ResourceManager.GetString("NullRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul nu poate fi nul..
        /// </summary>
        internal static string NullUser {
            get {
                return ResourceManager.GetString("NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul dat există deja..
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul a fost creat..
        /// </summary>
        internal static string RoleCreated {
            get {
                return ResourceManager.GetString("RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crearea rolului este imposibilă..
        /// </summary>
        internal static string RoleCreationImpossible {
            get {
                return ResourceManager.GetString("RoleCreationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul dat a fost șters..
        /// </summary>
        internal static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul dat nu a putut fi șters..
        /// </summary>
        internal static string RoleDeletionImpossible {
            get {
                return ResourceManager.GetString("RoleDeletionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ați eliminat toate rolurile..
        /// </summary>
        internal static string RoleDeletionNoRolesLeft {
            get {
                return ResourceManager.GetString("RoleDeletionNoRolesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul dat nu există..
        /// </summary>
        internal static string RoleDoesNotExist {
            get {
                return ResourceManager.GetString("RoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu există roluri pentru utilizatori..
        /// </summary>
        internal static string RolesDoNotExist {
            get {
                return ResourceManager.GetString("RolesDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolul a fost modificat..
        /// </summary>
        internal static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificarea rolului este imposibilă..
        /// </summary>
        internal static string RoleUpdateImpossible {
            get {
                return ResourceManager.GetString("RoleUpdateImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utilizator cu acest email ales există deja..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu s-a putut realiza autentificarea..
        /// </summary>
        internal static string UserAuthenticationImpossible {
            get {
                return ResourceManager.GetString("UserAuthenticationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de autentificare greșite..
        /// </summary>
        internal static string UserBadCredentials {
            get {
                return ResourceManager.GetString("UserBadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator creat cu succes..
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul a fost creat dar nu i s-au putut acorda rolurile..
        /// </summary>
        internal static string UserCreatedNoRole {
            get {
                return ResourceManager.GetString("UserCreatedNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crearea acestui utilizator este imposibilă..
        /// </summary>
        internal static string UserCreationImpossible {
            get {
                return ResourceManager.GetString("UserCreationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul dat a fost eliminat..
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul dat nu a putut fi șters..
        /// </summary>
        internal static string UserDeletionImpossible {
            get {
                return ResourceManager.GetString("UserDeletionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acest utilizator nu există..
        /// </summary>
        internal static string UserDeletionNoUserInDb {
            get {
                return ResourceManager.GetString("UserDeletionNoUserInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ați eliminat toți utilizatorii..
        /// </summary>
        internal static string UserDeletionNoUsersLeft {
            get {
                return ResourceManager.GetString("UserDeletionNoUsersLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acest utilizator nu există..
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul a fost modificat..
        /// </summary>
        internal static string UserEdited {
            get {
                return ResourceManager.GetString("UserEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul a fost modificat dar nu i s-au acordat rolurile. Roluri neatribuite: {0}..
        /// </summary>
        internal static string UserEditedNoRoles {
            get {
                return ResourceManager.GetString("UserEditedNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu s-a putut actualiza utilizatorul dat..
        /// </summary>
        internal static string UserEditImpossible {
            get {
                return ResourceManager.GetString("UserEditImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu au fost detectate schimbări în datele utilizatorului..
        /// </summary>
        internal static string UserModificationSameData {
            get {
                return ResourceManager.GetString("UserModificationSameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrarea utilizatorului imposibilă. Încercați din nou..
        /// </summary>
        internal static string UserRegistrationImpossible {
            get {
                return ResourceManager.GetString("UserRegistrationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator creat cu succes, dar nu toate rolurile au fost atribuite. Roluri neatribuite: {0}.
        /// </summary>
        internal static string UsersCreatedNoRoles {
            get {
                return ResourceManager.GetString("UsersCreatedNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu există utilizatori..
        /// </summary>
        internal static string UsersDoNotExist {
            get {
                return ResourceManager.GetString("UsersDoNotExist", resourceCulture);
            }
        }
    }
}
